# 02 Introduction to Numpy

## Contents

- [02.01 Understanding Data Types in Python](#0201-Understanding-Data-Types-in-Python)
    - [02.01.01 A Python Interger Is More Than Just an Integer](#020101-A-Python-Interger-Is-More-Than-Just-an-Integer)
    - [02.01.02 A Python List Is More Than Just a List](#020102-A-Python-List-Is-More-Than-Just-a-List)
    - [02.01.03 Fixed-Type Arrays in Python](#020103-Fixed-Type-Arrays-in-Python)
    - [02.01.04 Creating Arrays from Python Lists](#020104-Creating-Arrays-from-Python-Lists)
    - [02.01.05 Creating Arrays from Scratch](#020105-Creating-Arrays-from-Scratch)
    - [02.01.06 NumPy Standard Data Types](#020106-NumPy-Standard-Data-Types)
- [02.02 The Basics of Numpy Arrays](#0202-The-Basics-of-Numpy-Arrays)
- [02.03 Computation on Numpy Arrays: Universal Functions](#0203-Computation-on-Numpy-Arrays-Universal-Functions)
- [02.04 Aggregations: Min, Max, and Everything in Between](#0204-Aggregations-Min,-Max,-and-Everything-in-Between)
- [02.05 Computation on Arrays: Broadcasting](#0405-Computation-on-Arrays-Broadcasting)
- [02.06 Comparisons, Masks, and Boolean Logic](#0406-Comparisons,-Masks,-and-Boolean-Logic)
- [02.07 Fancy Indexing](#0407-Fancy-Indexing)
- [02.08 Sorting Arrays](#0408-Sorting-Arrays)
- [02.09 Structured Data: NumPy's Structured Arrays](#0209-Structured-Data-NumPy's-Structured-Arrays)

In [2]:
# import
import numpy as np
import scipy
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import IPython
import networkx as nx
import sklearn

from IPython.display import Image
%matplotlib inline

import datetime
dt = datetime.datetime.now()

print(
"""{}-{}-{} {}:{}:{}
----------------------
numpy\t\t{}
scipy\t\t{}
pandas\t\t{}
matplotlib\t{}
----------------------
ipython\t\t{}
----------------------
sklearn\t\t{}"""
    .format(dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second, np.__version__, scipy.__version__, pd.__version__, matplotlib.__version__, IPython.__version__, sklearn.__version__))

2019-3-31 16:44:49
----------------------
numpy		1.15.2
scipy		1.1.0
pandas		0.24.1
matplotlib	3.0.0
----------------------
ipython		7.2.0
----------------------
sklearn		0.20.0


## 02.01 Understanding Data Types in Python

In [6]:
result = 0
for i in range(100):
    result += 1

print('result: {}\ntype: {}'.format(result, type(result)))

result: 100
type: <class 'int'>


In [7]:
x = 4
print('type: {}'.format(type(x)))
x = 'four'
print('type: {}'.format(type(x)))

type: <class 'int'>
type: <class 'str'>


### 02.01.01 A Python Interger Is More Than Just an Integer

### 02.01.02 A Python List Is More Than Just a List

In [12]:
L = list(range(10))
print('L: {}'.format(L))
print('type: {}'.format(type(L[0])))

L: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
type: <class 'int'>


In [14]:
L2 = [str(c) for c in L]
print('L2: {}'.format(L2))
print('type: {}'.format(type(L2[0])))

L2: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
type: <class 'str'>


In [15]:
L3 = [True, '2', 3.0, 4]
print('type: {}'.format([type(item) for item in L3]))

type: [<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]


### 02.01.03 Fixed-Type Arrays in Python

In [16]:
import array
L = list(range(10))
A = array.array('i', L)
print(A)
print('type: {}'.format(type(A[0])))

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
type: <class 'int'>


### 02.01.04 Creating Arrays from Python Lists

In [3]:
L = np.array([1, 2, 3, 5, 8, 13])
print(L)

[ 1  2  3  5  8 13]


In [4]:
L = np.array([1, 2, 3, 5.0, 8, 13])
print(L)

[ 1.  2.  3.  5.  8. 13.]


In [5]:
L = np.array([1, 2, 3, 5, 8, 13], dtype='float32')
print(L)

[ 1.  2.  3.  5.  8. 13.]


In [6]:
L = np.array([range(i, i+3) for i in [2, 4, 6]])
print(L)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


### 02.01.05 Creating Arrays from Scratch

In [29]:
num = 10
zeros = np.zeros(num, dtype=int)
print('{} length array filled with 0s'.format(num))
print(zeros)

10 length array filled with 0s
[0 0 0 0 0 0 0 0 0 0]


In [28]:
row, col = 3, 5
ones = np.ones((row, col), dtype=float)
print('{}x{} floating-point array filled with 1s'.format(row, col))
print(ones)

3x5 floating-point array filled with 1s
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
row, col = 3, 5
val = 3.14
full = np.full((row, col), val)
print('{}x{} array filled with {}'.format(row, col, val))
print(full)

3x5 array filled with 3.14
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [26]:
start, end = 0, 20
step = 2
arange = np.arange(start, end, step)
print('start at {} end at {}, stepping by {}'.format(start, end, step))
print(arange)

start at 0 end at 20, stepping by 2
[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
start, end = 0, 1
num = 5
linspace = np.linspace(start, end, num)
print('{} values beteween {} and {}'.format(num, start, end))
print(linspace)

5 values beteween 0 and 1
[0.   0.25 0.5  0.75 1.  ]


In [24]:
row, col = 3, 3
random = np.random.random((row, col))
print('{}x{} array of uniforaly distributed'.format(row, col))
print(random)

3x3 array of uniforaly distributed
[[0.36112585 0.17324368 0.95683928]
 [0.2165086  0.52295807 0.97430295]
 [0.3465815  0.51126976 0.72872297]]


In [23]:
mean, std = 0, 1
row, col = 3, 3
normal = np.random.normal(mean, std, (row, col))
print('{}x{} array of normally distributed random\nmean {} std {}'.format(row, col, mean, std))
print(normal)

3x3 array of normally distributed random
mean 0 std 1
[[ 0.34947068  1.27760023 -0.0958526 ]
 [-0.91549194  1.18445305  0.63586514]
 [ 0.39018749  0.77889605  1.85747659]]


In [20]:
start, end = 0, 10
row, col = 3, 3
randint = np.random.randint(start, end, (row, col))
print('{}x{} array of random integers in [{}, {}]'.format(row, col, start, end))
print(randint)

3x3 array of random integers in [0, 10]
[[2 9 3]
 [4 3 3]
 [2 8 7]]


In [30]:
num = 3
eye = np.eye(num)
print('{}x{} identity mat'.format(num, num))
print(eye)

3x3 identity mat
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
num = 3
empty = np.empty(num)
print('uninialized array of {} integers'.format(num))
print(empty)

uninialized array of 3 integers
[1. 1. 1.]


### 02.01.06 NumPy Standard Data Types