# 02 Introduction to Numpy

## Contents

- [02.01 Understanding Data Types in Python](#02-01-Understanding-Data-Types-in-Python)
    - [02.01.01 A Python Interger Is More Than Just an Integer](#020101-A-Python-Interger-Is-More-Than-Just-an-Integer)
    - [02.01.02 A Python List Is More Than Just a List](#020102-A-Python-List-Is-More-Than-Just-a-List)
    - [02.01.03 Fixed-Type Arrays in Python](#020103-Fixed-Type-Arrays-in-Python)
    - [02.01.04 Creating Arrays from Python Lists](#020104-Creating-Arrays-from-Python-Lists)
    - [02.01.05 Creating Arrays from Scratch](#020105-Creating-Arrays-from-Scratch)
    - [02.01.06 NumPy Standard Data Types](#020106-NumPy-Standard-Data-Types)
- [02.02 The Basics of Numpy Arrays](#0202-The-Basics-of-Numpy-Arrays)
    - [02.02.01 NumPy Array Attributes](#020201-NumPy-Array-Attributes)
    - [02.02.02 Array Indexing: Accessing Single Elements](#020202-Array-Indexing-Accessing-Single-Elements)
    - [02.02.03 Array Slicing: Accessing Subarrays](#020203-Array-Slicing-Accessing-Subarrays)
        - [02.02.03.01 One-dimensional subarrays](#02020301-One-dimensional-subarrays)
        - [02.02.03.02 Multidimensional subarrays](#02020302-Multidimensional-subarrays)
        - [02.02.03.03 Accessing array rows and columns](#02020303-Accessing-array-rows-and-columns)
        - [02.02.03.04 Subarrays as no-copy views](#02020304-Subarrays-as-no-copy-views)
        - [02.02.03.05 Creating copies of arrays](#02020305-Creating-copies-of-arrays)
    - [02.02.04 Reshaping of Arrays](#020204-Reshaping-of-Arrays)
    - [02.02.05 Array Concatenation and Splitting](#020205-Array-Concatenation-and-Splitting)
        - [02.02.05.01 Concatenation of arrays](#02020501-Concatenation-of-arrays)
        - [02.02.05.02 Splitting of arrays](#02020502-Splitting-of-arrays)
- [02.03 Computation on Numpy Arrays: Universal Functions](#0203-Computation-on-Numpy-Arrays-Universal-Functions)
    - [02.03.01 The Slowness of Loops](#020301-The-Slowness-of-Loops)
    - [02.03.02 Introducing UFuncs](#020302-Introducing-UFuncs)
    - [02.03.03 Exploring NumPy's UFuncs](#020303-Exploring-NumPys-UFuncs)
        - [02.03.03.01 Array arithmetic](#02030301-Array-arithmetic)
        - [02.03.03.02 Absolute value](#02030302-Absolute-value)
        - [02.03.03.03 Trigometric functions](#02030303-Trigometric-functions)
        - [02.03.03.04 Exponents and logarithms](#02030304-Exponents-and-logarithms)
        - [02.03.03.05 Specialized ufuncs](#02030305-Specialized-ufuncs)
    - [02.03.04 Advanced Ufunc Features](#020304-Advanced-Ufunc-Features)
        - [02.03.04.01 Specifying output](#02030401-Specifying-output)
        - [02.03.04.02 Aggregates](#02030402-Aggregates)
        - [02.03.04.03 Outer products](#02030403-Outer-products)
    - [02.03.05 Ufuncs: Leanging More](#020305-Ufuncs-Leanging-More)
- [02.04 Aggregations: Min, Max, and Everything in Between](#0204-Aggregations-Min-Max-and-Everything-in-Between)
    - [02.04.01 Stumming the Values in an Array](#020401-Stumming-the-Values-in-an-Array)
- [02.05 Computation on Arrays: Broadcasting](#0405-Computation-on-Arrays-Broadcasting)
- [02.06 Comparisons, Masks, and Boolean Logic](#0406-Comparisons,-Masks,-and-Boolean-Logic)
- [02.07 Fancy Indexing](#0407-Fancy-Indexing)
- [02.08 Sorting Arrays](#0408-Sorting-Arrays)
- [02.09 Structured Data: NumPy's Structured Arrays](#0209-Structured-Data-NumPy's-Structured-Arrays)

In [2]:
# import
import numpy as np
import scipy
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import IPython
import networkx as nx
import sklearn

from IPython.display import Image
%matplotlib inline

import datetime
dt = datetime.datetime.now()

print(
"""{}-{}-{} {}:{}:{}
----------------------
numpy\t\t{}
scipy\t\t{}
pandas\t\t{}
matplotlib\t{}
----------------------
ipython\t\t{}
----------------------
sklearn\t\t{}"""
    .format(dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second, np.__version__, scipy.__version__, pd.__version__, matplotlib.__version__, IPython.__version__, sklearn.__version__))

2019-3-31 16:44:49
----------------------
numpy		1.15.2
scipy		1.1.0
pandas		0.24.1
matplotlib	3.0.0
----------------------
ipython		7.2.0
----------------------
sklearn		0.20.0


## 02.01 Understanding Data Types in Python

In [6]:
result = 0
for i in range(100):
    result += 1

print('result: {}\ntype: {}'.format(result, type(result)))

result: 100
type: <class 'int'>


In [7]:
x = 4
print('type: {}'.format(type(x)))
x = 'four'
print('type: {}'.format(type(x)))

type: <class 'int'>
type: <class 'str'>


### 02.01.01 A Python Interger Is More Than Just an Integer

### 02.01.02 A Python List Is More Than Just a List

In [12]:
L = list(range(10))
print('L: {}'.format(L))
print('type: {}'.format(type(L[0])))

L: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
type: <class 'int'>


In [14]:
L2 = [str(c) for c in L]
print('L2: {}'.format(L2))
print('type: {}'.format(type(L2[0])))

L2: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
type: <class 'str'>


In [15]:
L3 = [True, '2', 3.0, 4]
print('type: {}'.format([type(item) for item in L3]))

type: [<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]


### 02.01.03 Fixed-Type Arrays in Python

In [16]:
import array
L = list(range(10))
A = array.array('i', L)
print(A)
print('type: {}'.format(type(A[0])))

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
type: <class 'int'>


### 02.01.04 Creating Arrays from Python Lists

In [3]:
L = np.array([1, 2, 3, 5, 8, 13])
print(L)

[ 1  2  3  5  8 13]


In [4]:
L = np.array([1, 2, 3, 5.0, 8, 13])
print(L)

[ 1.  2.  3.  5.  8. 13.]


In [5]:
L = np.array([1, 2, 3, 5, 8, 13], dtype='float32')
print(L)

[ 1.  2.  3.  5.  8. 13.]


In [6]:
L = np.array([range(i, i+3) for i in [2, 4, 6]])
print(L)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


### 02.01.05 Creating Arrays from Scratch

In [29]:
num = 10
zeros = np.zeros(num, dtype=int)
print('{} length array filled with 0s'.format(num))
print(zeros)

10 length array filled with 0s
[0 0 0 0 0 0 0 0 0 0]


In [28]:
row, col = 3, 5
ones = np.ones((row, col), dtype=float)
print('{}x{} floating-point array filled with 1s'.format(row, col))
print(ones)

3x5 floating-point array filled with 1s
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
row, col = 3, 5
val = 3.14
full = np.full((row, col), val)
print('{}x{} array filled with {}'.format(row, col, val))
print(full)

3x5 array filled with 3.14
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [26]:
start, end = 0, 20
step = 2
arange = np.arange(start, end, step)
print('start at {} end at {}, stepping by {}'.format(start, end, step))
print(arange)

start at 0 end at 20, stepping by 2
[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
start, end = 0, 1
num = 5
linspace = np.linspace(start, end, num)
print('{} values beteween {} and {}'.format(num, start, end))
print(linspace)

5 values beteween 0 and 1
[0.   0.25 0.5  0.75 1.  ]


In [24]:
row, col = 3, 3
random = np.random.random((row, col))
print('{}x{} array of uniforaly distributed'.format(row, col))
print(random)

3x3 array of uniforaly distributed
[[0.36112585 0.17324368 0.95683928]
 [0.2165086  0.52295807 0.97430295]
 [0.3465815  0.51126976 0.72872297]]


In [23]:
mean, std = 0, 1
row, col = 3, 3
normal = np.random.normal(mean, std, (row, col))
print('{}x{} array of normally distributed random\nmean {} std {}'.format(row, col, mean, std))
print(normal)

3x3 array of normally distributed random
mean 0 std 1
[[ 0.34947068  1.27760023 -0.0958526 ]
 [-0.91549194  1.18445305  0.63586514]
 [ 0.39018749  0.77889605  1.85747659]]


In [20]:
start, end = 0, 10
row, col = 3, 3
randint = np.random.randint(start, end, (row, col))
print('{}x{} array of random integers in [{}, {}]'.format(row, col, start, end))
print(randint)

3x3 array of random integers in [0, 10]
[[2 9 3]
 [4 3 3]
 [2 8 7]]


In [30]:
num = 3
eye = np.eye(num)
print('{}x{} identity mat'.format(num, num))
print(eye)

3x3 identity mat
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
num = 3
empty = np.empty(num)
print('uninialized array of {} integers'.format(num))
print(empty)

uninialized array of 3 integers
[1. 1. 1.]


### 02.01.06 NumPy Standard Data Types

## 02.02 The Basics of Numpy Arrays

### 02.02.01 NumPy Array Attributes

In [36]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)#, seed=0)
x2 = np.random.randint(10, size=(3, 4))#, seed=0)
x3 = np.random.randint(10, size=(3, 4, 5))#, seed=0)
print('x1 = \n{}\n'.format(x1))
print('x2 = \n{}\n'.format(x2))
print('x3 = \n{}'.format(x3))

x1 = 
[5 0 3 3 7 9]

x2 = 
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

x3 = 
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [39]:
print('x3 ndim:\t{}'.format(x3.ndim))
print('x3 shape:\t{}'.format(x3.shape))
print('x3 size:\t{}'.format(x3.size))

x3 ndim:	3
x3 shape:	(3, 4, 5)
x3 size:	60


In [40]:
print('dtype: {}'.format(x3.dtype))

dtype: int64


In [41]:
print('itemsize: {} bytes'.format(x3.itemsize))
print('nbytes: {} bytes'.format(x3.nbytes))

itemsize: 8 bytes
nbytes: 480 bytes


### 02.02.02 Array Indexing: Accessing Single Elements

In [42]:
print('x1={}'.format(x1))
print('x1[0]={}'.format(x1[0]))
print('x1[4]={}'.format(x1[4]))

x1=[5 0 3 3 7 9]
x1[0]=5
x1[4]=7


In [43]:
print('x1[-1]={}'.format(x1[-1]))
print('x1[-2]={}'.format(x1[-2]))

x1[-1]=9
x1[-2]=7


In [60]:
print('x2=\n{}\n'.format(x2))
print('x2[0,0]={}\n'.format(x2[0,0]))
print('x2[2,0]={}\n'.format(x2[2,0]))
print('x2[2,-1]={}\n'.format(x2[2,-1]))

x2=
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

x2[0,0]=99

x2[2,0]=1

x2[2,-1]=7



In [46]:
x2[0,0]=12
print('x2=\n{}'.format(x2))

x2=
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [61]:
print('x1={}\n'.format(x1))
x1[0] = 3.14159
print('NumPy arrays have a fixed type\nx1={}'.format(x1))

x1=[3 0 3 3 7 9]

NumPy arrays have a fixed type
x1=[3 0 3 3 7 9]


### 02.02.03 Array Slicing: Accessing Subarrays

#### 02.02.03.01 One-dimensional subarrays

In [63]:
x = np.arange(10)
print('x={}\n'.format(x))
print('x[:5]={}\n'.format(x[:5]))
print('x[5:]={}\n'.format(x[5:]))
print('x[4:7]={}\n'.format(x[4:7]))
print('x[::2]={}\n'.format(x[::2]))
print('x[1::2]={}'.format(x[1::2]))

x=[0 1 2 3 4 5 6 7 8 9]

x[:5]=[0 1 2 3 4]

x[5:]=[5 6 7 8 9]

x[4:7]=[4 5 6]

x[::2]=[0 2 4 6 8]

x[1::2]=[1 3 5 7 9]


In [64]:
print('x[::-1]={}\n'.format(x[::-1]))
print('x[5::-2]={}'.format(x[5::-2]))

x[::-1]=[9 8 7 6 5 4 3 2 1 0]

x[5::-2]=[5 3 1]


#### 02.02.03.02 Multidimensional subarrays

In [67]:
print('x2 =\n{}\n'.format(x2))
print('x2[:2, :3] =\n{}\n'.format(x2[:2, :3]))
print('x2[:3, ::2] =\n{}\n'.format(x2[:3, ::2]))
print('x2[::-1, ::-1] =\n{}'.format(x2[::-1, ::-1]))

x2 =
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

x2[:2, :3] =
[[99  5  2]
 [ 7  6  8]]

x2[:3, ::2] =
[[99  2]
 [ 7  8]
 [ 1  7]]

x2[::-1, ::-1] =
[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 99]]


#### 02.02.03.03 Accessing array rows and columns

In [54]:
print('x2[:, 0]=\n{}'.format(x2[:, 0]))

x2[:, 0]=
[12  7  1]


In [55]:
print('x2[0, :]=\n{}'.format(x2[0, :]))

x2[0, :]=
[12  5  2  4]


In [56]:
print('x2[0]=\n{}'.format(x2[0]))

x2[0]=
[12  5  2  4]


#### 02.02.03.04 Subarrays as no-copy views

In [59]:
print('x2=\n{}\n'.format(x2))

x2_sub = x2[:2, :2]
print('x2_sub = x2[:2, :2] =\n{}\n'.format(x2_sub))

x2_sub[0, 0] = 99
print('x2_sub =\n{}\n'.format(x2_sub))

print('original array is changed\nx2 =\n{}\n'.format(x2))

x2=
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

x2_sub = x2[:2, :2] =
[[12  5]
 [ 7  6]]

x2_sub =
[[99  5]
 [ 7  6]]

original array is changed
x2 =
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]



#### 02.02.03.05 Creating copies of arrays

In [68]:
x2_sub_copy = x2[:2, :2].copy()
print('x2_sub_copy =\n{}\n'.format(x2_sub_copy))

x2_sub_copy[0, 0] = 42
print('x2_sub_copy =\n{}\n'.format(x2_sub_copy))

print('original arrays is NOT touched\nx2 =\n{}'.format(x2))

x2_sub_copy =
[[99  5]
 [ 7  6]]

x2_sub_copy =
[[42  5]
 [ 7  6]]

original arrays is NOT touched
x2 =
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### 02.02.04 Reshaping of Arrays

In [69]:
grid = np.arange(1, 10).reshape((3, 3))
print('grid =\n{}'.format(grid))

grid =
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
x = np.array([1, 2, 3])
print('x:\n{}\n'.format(x))
x.reshape((1, 3))
print('reshaped x:\n{}\n'.format(x))

print('x[np.newaxis, :]:\n{}\n'.format(x[np.newaxis, :]))

x.reshape((3, 1))
print('x.reshape((3, 1)):\n{}\n'.format(x.reshape((3, 1))))

print('x[:, np.newaxis]:\n{}'.format(x[:, np.newaxis]))

x:
[1 2 3]

reshaped x:
[1 2 3]

x[np.newaxis, :]:
[[1 2 3]]

x.reshape((3, 1)):
[[1]
 [2]
 [3]]

x[:, np.newaxis]:
[[1]
 [2]
 [3]]


### 02.02.05 Array Concatenation and Splitting

#### 02.02.05.01 Concatenation of arrays

In [79]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
x_y = np.concatenate([x, y])
print('np.concatenate([x, y]) :\n{}\n'.format(x_y))

z = [99, 99, 99]
print('np.concatenate([x, y, z]) :\n{}'.format(np.concatenate([x, y, z])))

np.concatenate([x, y]) :
[1 2 3 3 2 1]

np.concatenate([x, y, z]) :
[ 1  2  3  3  2  1 99 99 99]


In [81]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

print('concatenate along 1st axis :\n{}\n'.format(np.concatenate([grid, grid])))

print('concatenate along 2nd axis :\n{}'.format(np.concatenate([grid, grid], axis=1)))

concatenate along 1st axis :
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

concatenate along 2nd axis :
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [85]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], 
                 [6, 5, 4]])
print('vertically stack the arrays :\n{}\n'.format(np.vstack([x, grid])))

y = np.array([[99], 
              [99]])

print('horizontally stack the arrays :\n{}\n'.format(np.hstack([grid, y])))

z = np.array([[-2, -1, 0], 
              [-5, -4, -3]])

print('third axis :\n{}'.format(np.dstack([grid, z])))

vertically stack the arrays :
[[1 2 3]
 [9 8 7]
 [6 5 4]]

horizontally stack the arrays :
[[ 9  8  7 99]
 [ 6  5  4 99]]

third axis :
[[[ 9 -2]
  [ 8 -1]
  [ 7  0]]

 [[ 6 -5]
  [ 5 -4]
  [ 4 -3]]]


#### 02.02.05.02 Splitting of arrays

In [87]:
x = [1, 2, 3, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print('np.split(x, [3, 5])\nx1 = {}\nx2 = {}\nx3 = {}'.format(x1, x2, x3))

np.split(x, [3, 5])
x1 = [1 2 3]
x2 = [99  3]
x3 = [2 1]


In [88]:
grid = np.arange(16).reshape((4, 4))
print('grid :\n{}\n'.format(grid))
upper, lower = np.vsplit(grid, [2])
print('np.vsplit(grid, [2])\nupper = \n{}\nlower = \n{}'.format(upper, lower))

grid :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

np.vsplit(grid, [2])
upper = 
[[0 1 2 3]
 [4 5 6 7]]
lower = 
[[ 8  9 10 11]
 [12 13 14 15]]


In [90]:
left, right = np.hsplit(grid, [2])
print('np.hsplit(grid, [2])\nleft =\n{}\nright = \n{}'.format(left, right))

np.hsplit(grid, [2])
left =
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right = 
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [93]:
grid = np.arange(24).reshape((2, 3, 4))
superficial, deep = np.dsplit(grid, [2])
print('np.dsplit(grid, [2])\nsuperficial = \n{}\ndeep = \n{}'.format(superficial, deep))

np.dsplit(grid, [2])
superficial = 
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[12 13]
  [16 17]
  [20 21]]]
deep = 
[[[ 2  3]
  [ 6  7]
  [10 11]]

 [[14 15]
  [18 19]
  [22 23]]]


## 02.03 Computation on NumPy Arrays: Universal Functions

### 02.03.01 The Slowness of Loops

In [103]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
        return output
    
values = np.random.randint(1, 10, size=5)
print(values)
compute_reciprocals(values)

[6 1 4 4 8]


array([1.66666667e-001, 4.94065646e-324, 1.97626258e-323, 1.97626258e-323,
       3.95252517e-323])

In [110]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

38.3 µs ± 1.68 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 02.03.02 Introducing UFuncs

In [105]:
print(compute_reciprocals(values))
print(1.0 / values)

[1.66666667e-001 4.94065646e-324 1.97626258e-323 1.97626258e-323
 3.95252517e-323]
[0.16666667 1.         0.25       0.25       0.125     ]


In [111]:
%timeit (1.0 / big_array)

4 ms ± 93.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [107]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [109]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

### 02.03.03 Exploring NumPy's UFuncs

#### 02.03.03.01 Array arithmetic

In [130]:
x = np.arange(4)
print('x\t= {}'.format(x))
print('x + 5\t= {}'.format(x+5))
print('x - 5\t= {}'.format(x-5))
print('x * 2\t= {}'.format(x*2))
print('x / 2\t= {}'.format(x/2))
print('x // 2\t= {}'.format(x//2))
print('-x\t= {}'.format(-x))
print('x ** 2\t= {}'.format(x ** 2))
print('x % 2\t= {}'.format(x % 2))
print('-(0.5 * x + 1)**2\n\t= {}'.format(-(0.5*x+1)**2))

x	= [0 1 2 3]
x + 5	= [5 6 7 8]
x - 5	= [-5 -4 -3 -2]
x * 2	= [0 2 4 6]
x / 2	= [0.  0.5 1.  1.5]
x // 2	= [0 0 1 1]
-x	= [ 0 -1 -2 -3]
x ** 2	= [0 1 4 9]
x % 2	= [0 1 0 1]
-(0.5 * x + 1)**2
	= [-1.   -2.25 -4.   -6.25]


In [128]:
print('np.add(x, 5)\t\t= {}'.format(np.add(x, 5)))
print('np.subtract(x, 5)\t= {}'.format(np.subtract(x, 5)))
print('np.multiply(x, 2)\t= {}'.format(np.multiply(x, 2)))
print('np.divide(x, 2)\t\t= {}'.format(np.divide(x, 2)))
print('np.floor_divide(x, 2)\t= {}'.format(np.floor_divide(x, 2)))
print('np.negative(x)\t\t= {}'.format(np.negative(x)))
print('np.power(x, 2)\t\t= {}'.format(np.power(x, 2)))
print('np.mod(x, 2)\t\t= {}'.format(np.mod(x, 2)))
print('np.negative(np.power(np.add(np.multiply(.5, x), 1), 2))\n\t\t\t= {}'.format(np.negative(np.power(np.add(np.multiply(.5, x), 1), 2))))

np.add(x, 5)		= [5 6 7 8]
np.subtract(x, 5)	= [-5 -4 -3 -2]
np.multiply(x, 2)	= [0 2 4 6]
np.divide(x, 2)		= [0.  0.5 1.  1.5]
np.floor_divide(x, 2)	= [0 0 1 1]
np.negative(x)		= [ 0 -1 -2 -3]
np.power(x, 2)		= [0 1 4 9]
np.mod(x, 2)		= [0 1 0 1]
np.negative(np.power(np.add(np.multiply(.5, x), 1), 2))
			= [-1.   -2.25 -4.   -6.25]


#### 02.03.03.02 Absolute value

In [134]:
x = np.array([-2, -1, 0, 1, 2])
print('abs(x)\t\t= {}'.format(abs(x)))
print('np.absolute(x)\t= {}'.format(np.absolute(x)))
print('np.abs(x)\t= {}'.format(np.abs(x)))

abs(x)		= [2 1 0 1 2]
np.absolute(x)	= [2 1 0 1 2]
np.abs(x)	= [2 1 0 1 2]


In [135]:
x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print('np.abs(x)\t= {}'.format(np.abs(x)))

np.abs(x)	= [5. 5. 2. 1.]


#### 02.03.03.03 Trigometric functions

In [137]:
theta = np.linspace(0, np.pi, 3)
print('theta\t\t= {}'.format(theta))
print('np.sin(theta)\t= {}'.format(np.sin(theta)))
print('np.cos(theta)\t= {}'.format(np.cos(theta)))
print('np.tan(theta)\t= {}'.format(np.tan(theta)))

theta		= [0.         1.57079633 3.14159265]
np.sin(theta)	= [0.0000000e+00 1.0000000e+00 1.2246468e-16]
np.cos(theta)	= [ 1.000000e+00  6.123234e-17 -1.000000e+00]
np.tan(theta)	= [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [138]:
x = [-1, 0, 1]
print('x\t\t= {}'.format(x))
print('p.arcsin(x)\t= {}'.format(np.arcsin(x)))
print('p.arccos(x)\t= {}'.format(np.arccos(x)))
print('p.arctan(x)\t= {}'.format(np.arctan(x)))

x		= [-1, 0, 1]
p.arcsin(x)	= [-1.57079633  0.          1.57079633]
p.arccos(x)	= [3.14159265 1.57079633 0.        ]
p.arctan(x)	= [-0.78539816  0.          0.78539816]


#### 02.03.03.04 Exponents and logarithms

In [139]:
x = [1, 2, 3]
print('x\t= {}'.format(x))
print('e^x\t= {}'.format(np.exp(x)))
print('2^x\t= {}'.format(np.exp2(x)))
print('3^x\t= {}'.format(np.power(3, x)))

x	= [1, 2, 3]
e^x	= [ 2.71828183  7.3890561  20.08553692]
2^x	= [2. 4. 8.]
3^x	= [ 3  9 27]


In [141]:
x = [1, 2, 4, 10]
print('x\t= {}'.format(x))
print('ln(x)\t= {}'.format(np.log(x)))
print('log2(x)\t= {}'.format(np.log2(x)))
print('log10(x)= {}'.format(np.log10(x)))

x	= [1, 2, 4, 10]
ln(x)	= [0.         0.69314718 1.38629436 2.30258509]
log2(x)	= [0.         1.         2.         3.32192809]
log10(x)= [0.         0.30103    0.60205999 1.        ]


In [142]:
x = [0, 0.001, 0.01, 0.1]
print('exp(x) - 1 = {}'.format(np.expm1(x)))
print('log(1 + x) = {}'.format(np.log1p(x)))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


#### 02.03.03.05 Specialized ufuncs

In [143]:
from scipy import special

x = [1, 5, 10]
print('gamma(x)\t= {}'.format(special.gamma(x)))
print('ln|gamma(x)|\t= {}'.format(special.gammaln(x)))
print('beta(x, 2)\t= {}'.format(special.beta(x, 2)))

gamma(x)	= [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)|	= [ 0.          3.17805383 12.80182748]
beta(x, 2)	= [0.5        0.03333333 0.00909091]


In [145]:
x = np.array([0, 0.3, 0.7, 1.0])
print('erf(x)\t\t= {}'.format(special.erf(x)))
print('erfc(x)\t\t= {}'.format(special.erfc(x)))
print('erfinv(x)\t= {}'.format(special.erfinv(x)))

erf(x)		= [0.         0.32862676 0.67780119 0.84270079]
erfc(x)		= [1.         0.67137324 0.32219881 0.15729921]
erfinv(x)	= [0.         0.27246271 0.73286908        inf]


### 02.03.04 Advanced Ufunc Features

#### 02.03.04.01 Specifying output

In [146]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print('y = {}'.format(y))

y = [ 0. 10. 20. 30. 40.]


In [149]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print('y = {}'.format(y))

y = [ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [162]:
n = 100000000
x = np.arange(n)
y = np.zeros(n*2)
%timeit y[::2] = 2 ** x
%timeit np.power(2, x, out=y[::2])

14.2 s ± 902 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
12.3 s ± 613 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 02.03.04.02 Aggregates

In [170]:
x = np.arange(1, 6)
print('np.add.reduce(x)\t\t= {}'.format(np.add.reduce(x)))
print('np.multiply.reduce(x)\t\t= {}'.format(np.multiply.reduce(x)))
print('np.add.accumulate(x)\t\t= {}'.format(np.add.accumulate(x)))
print('np.multiply.accumulate(x)\t= {}'.format(np.multiply.accumulate(x)))

np.add.reduce(x)		= 15
np.multiply.reduce(x)		= 120
np.add.accumulate(x)		= [ 1  3  6 10 15]
np.multiply.accumulate(x)	= [  1   2   6  24 120]


In [175]:
print('np.sum(x)\t= {}'.format(np.sum(x)))
print('np.prod(x)\t= {}'.format(np.prod(x)))
print('np.cumsum(x)\t= {}'.format(np.cumsum(x)))
print('np.cumprod(x)\t= {}'.format(np.cumprod(x)))

np.sum(x)	= 15
np.prod(x)	= 120
np.cumsum(x)	= [ 1  3  6 10 15]
np.cumprod(x)	= [  1   2   6  24 120]


#### 02.03.04.03 Outer products

In [176]:
x = np.arange(1, 6)
print('np.multiply.outer(x, x)=\n{}'.format(np.multiply.outer(x, x)))

np.multiply.outer(x, x)=
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


### 02.03.05 Ufuncs: Leanging More

## 02.04 Aggregations: Min, Max, and Everything in Between

### 02.04.01 Summing the Values in an Array

In [189]:
np.random.seed(0)
L = np.random.random(100)

print('sum(L)\t\t= {}'.format(sum(L)))
print('np.sum(L)\t= {}'.format(np.sum(L)))

sum(L)		= 47.27938395125176
np.sum(L)	= 47.279383951251766


In [190]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

103 ms ± 1.91 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
609 µs ± 7.27 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
